version: '3'

services:
  mariadb-test:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.mariadb-cypress
    environment:
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
    hostname: kontext_mariadb_1
    volumes:
      - kontext_testdb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - databases
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--password=$MYSQL_ROOT_PASSWORD"]
      interval: 1s
      timeout: 10s
      retries: 5

  kontext:
    build:
      dockerfile: dockerfiles/Dockerfile.kontext-cypress-jammy
    volumes:
      - ./scripts/install/conf/docker/config.cypress.xml:/opt/kontext/conf/config.xml
    depends_on:
      mariadb-test:
        condition: service_healthy
    networks:
      - databases

  rq-scheduler:
    depends_on:
      mariadb-test:
        condition: service_healthy
      redis:
        condition: service_healthy
      kontext:
        condition: service_started
    restart: always

  rq-worker:
    depends_on:
      mariadb-test:
        condition: service_healthy
      redis:
        condition: service_healthy
      kontext:
        condition: service_started
    networks:
      - databases

volumes:
  kontext_testdb: {}


networks:
  databases: {}