services:
  kontext-test:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.kontext

    command: bash -c "pip3 install pulp piwikapi && python3 tests/runtests.py"
    environment:
      - REDIS_HOST=kontext-redis-1
    volumes:
      - ./tests:/opt/kontext/tests
      - ./test-data:/opt/kontext/test-data
    networks:
      - databases
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:alpine
    networks:
      - databases
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 10s
      retries: 5

networks:
  databases: {}
