services:
  frodo:
    build: ${FRODO_PATH}
    ports:
      - 8088:8088
    networks:
      - kontext
      - databases
    command: bash -c "export PATH=$PATH:/usr/local/go/bin && curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b /usr/local/go/bin && air"
    volumes:
      - ${FRODO_PATH}:/opt/frodo
      - ./scripts/install/conf/docker/conf.frodo.json:/opt/frodo/conf.docker.json
      - ./scripts/install/conf/docker/air.frodo.toml:/opt/frodo/.air.toml
      - corpora-data:/var/lib/manatee

volumes:
  corpora-data: {}

networks:
  kontext: {}
  databases: {}