/*
 * Copyright (c) 2016 Charles University in Prague, Faculty of Arts,
 *                    Institute of the Czech National Corpus
 * Copyright (c) 2016 Tomas Machalek <tomas.machalek@gmail.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2
 * dated June, 1991.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

import { IFullActionControl } from 'kombo';
import { Observable, of as rxOf } from 'rxjs';
import { tap } from 'rxjs/operators';
import { tuple, pipe, Dict, List, HTTP, id } from 'cnc-tskit';

import { Kontext } from '../../types/common';
import { AjaxResponse } from '../../types/ajaxResponses';
import { PageModel } from '../../app/page';
import { QueryContextModel } from './context';
import { validateNumber, setFormItemInvalid } from '../../models/base';
import { GeneralQueryFormProperties, QueryFormModel, QueryFormModelState,
    FilterServerArgs, determineSupportedWidgets } from './common';
import { ActionName, Actions } from './actions';
import { ActionName as ConcActionName, Actions as ConcActions } from '../concordance/actions';
import { ActionName as MainMenuActionName, Actions as MainMenuActions } from '../mainMenu/actions';
import { PluginInterfaces } from '../../types/plugins';
import { TextTypesModel } from '../textTypes/main';
import { AjaxConcResponse } from '../concordance/common';
import { QueryType, AnyQuery, AdvancedQuery, SimpleQuery, parseSimpleQuery } from './query';
import { highlightSyntaxStatic } from './cqleditor/parser';


/**
 * This interface encodes values of multiple filter values. Array indices
 * should match query pipeline with non-filter ones represented by
 * 'undefined'.
 */
export interface FilterFormProperties extends GeneralQueryFormProperties {
    filters:Array<string>;
    maincorps:{[sourceId:string]:string};
    currQueryTypes:{[sourceId:string]:QueryType};
    // current queries values (e.g. when restoring a form state)
    currQueries:{[sourceId:string]:string};
    currDefaultAttrValues:{[sourceId:string]:string};
    currUseRegexpValues:{[sourceId:string]:boolean};
    tagBuilderSupport:{[sourceId:string]:boolean};
    currLposValues:{[sourceId:string]:string};
    currQmcaseValues:{[sourceId:string]:boolean};
    currInclkwicValues:{[sourceId:string]:boolean};
    inputLanguage:string;
    currPnFilterValues:{[sourceId:string]:string};
    currFilflVlaues:{[sourceId:string]:'f'|'l'};
    currFilfposValues:{[sourceId:string]:string};
    currFiltposValues:{[sourceId:string]:string};
    withinArgValues:{[sourceId:string]:boolean};
    opLocks:{[sourceId:string]:boolean};
    hasLemma:{[sourceId:string]:boolean};
    isAnonymousUser:boolean;
}

export function isFilterFormProperties(v:FilterFormProperties|AjaxResponse.FilterFormArgs):v is FilterFormProperties {
    return Array.isArray(v['filters']) && typeof v['maincorps'] === 'object';
}

/**
 * import {GeneralViewOptionsModel} from '../options/general';
 */
export function fetchFilterFormArgs<T extends
        AjaxResponse.FilterFormArgs[keyof AjaxResponse.FilterFormArgs]>(
    args:{[ident:string]:AjaxResponse.ConcFormArgs},
    initialArgs:AjaxResponse.FilterFormArgs,
    key:(item:AjaxResponse.FilterFormArgs)=>T

):{[sourceId:string]:T} {
    return pipe(
        args,
        Dict.filter((v, _) => v.form_type === Kontext.ConcFormTypes.FILTER),
        Dict.map((args, _) => key(<AjaxResponse.FilterFormArgs>args)),
        (data) => ({...data, '__new__': key(initialArgs)})
    );
}


export interface FilterFormModelState extends QueryFormModelState {

    maincorps:{[key:string]:string};

    lposValues:{[key:string]:string};

    pnFilterValues:{[key:string]:string};

    /**
     * Highlighted token FIRST/LAST. Specifies which token is highlighted.
     * This applies in case multiple matching tokens are found.
     */
    filflValues:{[key:string]:'f'|'l'};

    /**
     * Left range
     */
    filfposValues:{[key:string]:Kontext.FormValue<string>};

    /**
     * Right range
     */
    filtposValues:{[key:string]:Kontext.FormValue<string>};

    /**
     * Include kwic checkbox
     */
    inclkwicValues:{[key:string]:boolean};

    withinArgs:{[key:string]:boolean};

    hasLemma:{[key:string]:boolean};

    /**
     * If true for a certain key then the operation cannot be edited.
     * (this applies e.g. for filters generated by manual line
     * selection).
     */
    opLocks:{[key:string]:boolean};

    inputLanguage:string;
}

/**
 * Import form values either from a special properties object or from
 * an Ajax response used e.g. when replaying an operation.
 */
function importFormValues(src:FilterFormProperties):{[key:string]:AnyQuery};
function importFormValues(src:AjaxResponse.FilterFormArgs, sourceId:string):{[key:string]:AnyQuery};
function importFormValues(src:any, sourceId?:string):{[key:string]:AnyQuery} {
    if (isFilterFormProperties(src)) {
        return pipe(
            sourceId ? [sourceId] : Dict.keys(src.currQueries),
            List.map(
                filter => {
                    if (src.currQueryTypes[filter] === 'advanced') {
                        const query = src.currQueries[filter] || '';
                        const [queryHtml,] = highlightSyntaxStatic(
                            query,
                            'advanced',
                            {translate: id}
                        );
                        return tuple<string, AdvancedQuery>(
                            filter,
                            {
                                corpname: filter,
                                qtype: 'advanced',
                                query,
                                queryHtml,
                                pcq_pos_neg: 'pos',
                                include_empty: false,
                                default_attr: src.currDefaultAttrValues[filter],
                                suggestions: null
                            }
                        );

                    } else {
                        const query = src.currQueries[filter] || '';
                        return tuple<string, SimpleQuery>(
                            filter,
                                {
                                corpname: filter,
                                qtype: 'simple',
                                queryParsed: parseSimpleQuery(
                                    src.currQueries[filter] || '',
                                    src.currDefaultAttrValues[filter]
                                ),
                                query,
                                queryHtml: query,
                                qmcase: src.currQmcaseValues[filter],
                                pcq_pos_neg: 'pos',
                                include_empty: false,
                                default_attr: src.currDefaultAttrValues[filter],
                                use_regexp: src.currUseRegexpValues[filter]
                            }
                        )
                    }
                }
            ),
            Dict.fromEntries()
        );

    } else if (sourceId && AjaxResponse.isFilterFormArgs(src)) {
        return {
            [sourceId]: src.query_type === 'advanced' ?
                {
                    corpname: sourceId,
                    qtype: 'advanced',
                    query: src.query,
                    queryHtml: src.query,
                    pcq_pos_neg: 'pos',
                    include_empty: false,
                    default_attr: src.default_attr,
                    suggestions: null
                } :
                {
                    corpname: sourceId,
                    qtype: 'simple',
                    queryParsed: parseSimpleQuery(
                        src.query,
                        src.default_attr
                    ),
                    query: src.query,
                    queryHtml: src.query,
                    qmcase: src.qmcase,
                    pcq_pos_neg: 'pos',
                    include_empty: false,
                    default_attr: src.default_attr,
                    use_regexp: src.use_regexp
                }
        };

    } else {
        throw new Error('Failed to initialize filter form - invalid source object');
    }
}

/**
 * FilterFormModel handles all the filtsters applied within a query "pipeline".
 * Each filter is identified by its database ID (i.e. a key used by conc_persistence
 * plug-in to store it). Please note that it does not know the order of filters
 * in pipeline (it is up to QueryReplay store to handle this).
 */
export class FilterFormModel extends QueryFormModel<FilterFormModelState> {

    private readonly syncInitialArgs:AjaxResponse.FilterFormArgs;

    constructor(
            dispatcher:IFullActionControl,
            pageModel:PageModel,
            textTypesModel:TextTypesModel,
            queryContextModel:QueryContextModel,
            props:FilterFormProperties,
            syncInitialArgs:AjaxResponse.FilterFormArgs) {
        const queries:{[sourceId:string]:AnyQuery} = {
            ...importFormValues(props)
        };

        const tagBuilderSupport = props.tagBuilderSupport;
        super(
            dispatcher,
            pageModel,
            textTypesModel,
            queryContextModel,
            'filter-form-model',
            props,
            {
                formType: Kontext.ConcFormTypes.FILTER,
                forcedAttr: '', // TODO
                attrList: [...props.attrList],
                structAttrList: [...props.structAttrList],
                wPoSList: [], // TODO
                currentAction: 'filter_form',
                queries, // corpname|filter_id -> query
                rawAnchorIdx: {},
                rawFocusIdx: {},
                parsedAttrs: {},
                focusedAttr: {},
                cqlEditorMessages: {},
                useCQLEditor: props.useCQLEditor,
                tagAttr: props.tagAttr,
                widgetArgs: {}, // TODO
                maincorps: {...props.maincorps},
                downArrowTriggersHistory: pipe(
                    queries,
                    Dict.map(v => false),
                ),
                currentSubcorp: pageModel.getCorpusIdent().usesubcorp,
                lposValues: {...props.currLposValues},
                pnFilterValues: {...props.currPnFilterValues},
                filflValues: {...props.currFilflVlaues},
                filfposValues: pipe(
                    props.currFilfposValues,
                    Dict.map((v, fid) => Kontext.newFormValue(v, true))
                ),
                filtposValues: pipe(
                    props.currFiltposValues,
                    Dict.map((v, fid) => Kontext.newFormValue(v, true)),
                ),
                inclkwicValues: {...props.currInclkwicValues},
                tagBuilderSupport: {...tagBuilderSupport},
                opLocks: {...props.opLocks},
                activeWidgets: pipe(
                    props.filters,
                    List.map(item => tuple(item, null)),
                    Dict.fromEntries()
                ),
                withinArgs: {...props.withinArgValues},
                hasLemma: {...props.hasLemma},
                inputLanguage: props.inputLanguage,
                isAnonymousUser: props.isAnonymousUser,
                supportedWidgets: determineSupportedWidgets(
                    queries,
                    tagBuilderSupport,
                    props.isAnonymousUser
                ),
                contextFormVisible: false,    // TODO load from some previous state?
                textTypesFormVisible: false,  // dtto
                queryOptionsVisible: pipe(
                    props.filters,
                    List.map(item => tuple(item, true)),
                    Dict.fromEntries()
                ),    // dtto
                historyVisible: pipe(
                    queries,
                    Dict.keys(),
                    List.map(k => tuple(k, false)),
                    Dict.fromEntries()
                ),
                suggestionsVisible: pipe(
                    queries,
                    Dict.keys(),
                    List.map(k => tuple(k, false)),
                    Dict.fromEntries()
                ),
                suggestionsEnabled: props.suggestionsEnabled,
                isBusy: false,
                simpleQueryAttrSeq: []
        });
        this.syncInitialArgs = syncInitialArgs;

        this.addActionHandler<MainMenuActions.ShowFilter>(
            MainMenuActionName.ShowFilter,
            action => {
                this.syncFrom(rxOf({...this.syncInitialArgs, ...action.payload}));
            }
        );

        this.addActionSubtypeHandler<Actions.QueryInputSetLpos>(
            ActionName.QueryInputSetLpos,
            action => action.payload.formType === 'filter',
            action => {
                this.changeState(state => {
                    state.lposValues[action.payload.sourceId] = action.payload.lpos;
                });
            }
        );

        this.addActionSubtypeHandler<Actions.FilterInputSetPCQPosNeg>(
            ActionName.FilterInputSetPCQPosNeg,
            action => action.payload.formType === 'filter',
            action => {
                this.changeState(state => {
                    state.pnFilterValues[action.payload.filterId] = action.payload.value;
                });
            }
        );

        this.addActionHandler<Actions.FilterInputSetFilfl>(
            ActionName.FilterInputSetFilfl,
            action => {
                this.changeState(state => {
                    state.filflValues[action.payload.filterId] = action.payload.value;
                });
            }
        );

        this.addActionHandler<Actions.FilterInputSetRange>(
            ActionName.FilterInputSetRange,
            action => {
                this.changeState(state => {
                    this.setFilPosValue(
                        state,
                        action.payload.filterId,
                        action.payload.value,
                        action.payload.rangeId
                    );
                });
            }
        );

        this.addActionHandler<Actions.FilterInputSetInclKwic>(
            ActionName.FilterInputSetInclKwic,
            action => {
                this.changeState(state => {
                    state.inclkwicValues[action.payload.filterId] = action.payload.value;
                });
            }
        );

        this.addActionHandler<Actions.ApplyFilter>(
            ActionName.ApplyFilter,
            action => {
                let err:Error;
                this.changeState(state => {
                    err = this.validateForm(state, action.payload.filterId);
                    if (err) {
                        return;
                    }
                    err = this.testQueryNonEmpty(action.payload.filterId);
                    if (err) {
                        return;
                    }
                    err = this.testQueryTypeMismatch();
                });
                if (!err) {
                    this.changeState(state => {
                        state.isBusy = true;
                    });
                    this.submitQuery(
                        action.payload.filterId,
                        this.pageModel.getConcArgs().q.substr(1)
                    ).pipe(
                        tap(
                            (data) => {
                                this.pageModel.updateConcPersistenceId(data.conc_persistence_op_id);
                                this.changeState(state => {
                                    state.isBusy = false;
                                });
                            }
                        )
                    ).subscribe(
                        (data) => {
                            dispatcher.dispatch<ConcActions.AddedNewOperation>({
                                name: ConcActionName.AddedNewOperation,
                                payload: {
                                    concId: data.conc_persistence_op_id,
                                    data
                                }
                            });

                        },
                        (err) => {
                            this.pageModel.showMessage('error', err);
                        }
                    )

                } else {
                    this.pageModel.showMessage('error', err);
                }
            }
        );

        this.addActionHandler<Actions.QueryContextToggleForm>(
            ActionName.QueryContextToggleForm,
            action => {
                this.changeState(state => {
                    state.contextFormVisible = !state.contextFormVisible;
                });
            }
        );

        this.addActionHandler<Actions.QueryTextTypesToggleForm>(
            ActionName.QueryTextTypesToggleForm,
            action => {
                this.changeState(state => {
                    state.textTypesFormVisible = !state.textTypesFormVisible;
                });
            }
        );
    }

    private validateForm(state:FilterFormModelState, filterId:string):Error|null {
        if (validateNumber(state.filfposValues[filterId].value)) {
            state.filfposValues[filterId] = setFormItemInvalid(
                state.filfposValues[filterId], false);

        } else {
            state.filfposValues[filterId] = setFormItemInvalid(
                state.filfposValues[filterId], true);
            return new Error(this.pageModel.translate('global__invalid_number_format'));
        }

        if (validateNumber(state.filtposValues[filterId].value)) {
            state.filtposValues[filterId] = setFormItemInvalid(
                state.filtposValues[filterId], false);

        } else {
            state.filtposValues[filterId] = setFormItemInvalid(
                state.filtposValues[filterId], true);
            return new Error(this.pageModel.translate('global__invalid_number_format'));
        }
    }

    private setFilPosValue(state:FilterFormModelState, filterId:string, value:string,
            rangeId:string):void {
        if (rangeId === 'filfpos') {
            state.filfposValues[filterId] = {
                value,
                isInvalid: false,
                isRequired: true
            };

        } else if (rangeId === 'filtpos') {
            state.filtposValues[filterId] = {
                value,
                isInvalid: false,
                isRequired: true
            };
        }
    }

    /**
     * Synchronize user input values from an external source
     * (typically a server response or a local cache).
     */
    syncFrom(fn:Observable<AjaxResponse.FilterFormArgs>):Observable<AjaxResponse.FilterFormArgs> {
        return fn.pipe(
            tap(
                (data) => {
                    const filterId = data.op_key;
                    if (data.form_type === Kontext.ConcFormTypes.FILTER) {
                        this.changeState(state => {
                            state.queries = {...state.queries, ...importFormValues(data, filterId)};
                            state.maincorps[filterId] = data.maincorp;
                            state.pnFilterValues[filterId] = data.pnfilter;
                            state.filflValues[filterId] = data.filfl;
                            state.filfposValues[filterId] = {
                                value: data.filfpos,
                                isInvalid: false,
                                isRequired: true
                            };
                            state.filtposValues[filterId] = {
                                value: data.filtpos,
                                isInvalid: false,
                                isRequired: true
                            };
                            state.inclkwicValues[filterId] = data.inclkwic;
                            state.tagBuilderSupport[filterId] = data.tag_builder_support;
                            state.withinArgs[filterId] = data.within;
                            state.lposValues[filterId] = data.lpos;
                            state.hasLemma[filterId] = data.has_lemma;
                            state.opLocks[filterId] = false;
                            state.supportedWidgets = determineSupportedWidgets(
                                state.queries,
                                state.tagBuilderSupport,
                                state.isAnonymousUser
                            );
                        });

                    } else if (data.form_type === Kontext.ConcFormTypes.LOCKED ||
                            data.form_type === Kontext.ConcFormTypes.LGROUP) {
                        this.changeState(state => {
                            state.opLocks[filterId] = true;
                        });

                    } else {
                        throw new Error(
                            'Cannot sync filter model - invalid form data type: ' + data.form_type);
                    }
                }
            )
        );
    }

    private createSubmitArgs(filterId:string, concId:string):FilterServerArgs {
        const query = this.state.queries[filterId];
        return {
            type:'filterQueryArgs',
            qtype: query.qtype,
            query: query.query,
            default_attr: query.default_attr,
            qmcase: query.qtype === 'simple' ? query.qmcase : false,
            use_regexp: query.qtype === 'simple' ? query.use_regexp : false,
            pnfilter: this.state.pnFilterValues[filterId],
            filfl: this.state.filflValues[filterId],
            filfpos: this.state.filfposValues[filterId].value,
            filtpos: this.state.filtposValues[filterId].value,
            inclkwic: this.state.inclkwicValues[filterId] ? 1 : 0,
            within: this.state.withinArgs[filterId],
            ...this.pageModel.getConcArgs(),
            q: '~' + concId
        }
    }

    /**
     *
     * @param filterId id of filter operation (__new__ for new, conc ID if already applied)
     * @param concId concID we want to attach the submit to (it may or may not be equal to filterId)
     */
    submitQuery(filterId:string, concId:string):Observable<AjaxConcResponse> {
        const args = this.createSubmitArgs(filterId, concId);
        return this.pageModel.ajax$<AjaxConcResponse>(
            HTTP.Method.POST,
            this.pageModel.createActionUrl(
                'filter',
                [
                    ['format', 'json'],
                    ['q', '~' + concId]
                ]
            ),
            args,
            {
                contentType: 'application/json'
            }
        );
    }
}
