FROM czcorpus/kontext-manatee

SHELL ["/bin/bash", "--login", "-c"]
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
RUN nvm install node

WORKDIR /opt/kontext
COPY ./pack*.json ./
RUN npm install

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY ./conf ./conf
RUN python3 scripts/install/steps.py SetupKontext
RUN mkdir /var/log/rq

COPY ./scripts/install/install-min-ffmpeg.sh ./scripts/install/install-min-ffmpeg.sh
RUN apt-get install libmp3lame0 libmp3lame-dev
RUN python3 scripts/install/steps.py SetupFFMpeg

COPY launcher-config.json launcher-menu.json tsconfig.json webpack.dev.js ./