FROM czcorpus/kontext-manatee:2.225.8-jammy

WORKDIR /opt/kontext
COPY . .
RUN apt-get update \
    && apt-get install -y sox libsox-fmt-mp3 python3-pip python3-icu libcairo2 python3-lxml \
    && pip3 install --upgrade pip \
    && sed '/PyICU/d' ./requirements.txt | pip3 install -r /dev/stdin  \
    && python3 scripts/install/steps.py SetupKontext \
    && mkdir /var/log/rq  \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

CMD [ "python3",  "worker/rqworker.py" ]