FROM czcorpus/kontext-manatee:2.208-jammy

SHELL ["/bin/bash", "--login", "-c"]

COPY ./pack*.json ./
COPY launcher-config.json launcher-menu.json tsconfig.json webpack.dev.js ./
COPY requirements.txt ./
COPY ./conf ./conf

RUN apt-get update \
    && apt-get install -y sox libsox-fmt-mp3 nodejs npm python3-pip python3-icu \
    && npm install \
    && pip3 install --upgrade pip \
    && sed '/PyICU/d' ./requirements.txt | pip3 install -r /dev/stdin  \
    && python3 scripts/install/steps.py SetupKontext \
    && mkdir /var/log/rq  \
    && mkdir /var/local/corpora/query_persistence \
    && apt-get -y autoremove \
    && rm -rf /usr/local/src/manatee-open-2.167.10 \
    && rm -rf /var/lib/apt/lists/*