FROM czcorpus/kontext-manatee:2.225.8

SHELL ["/bin/bash", "--login", "-c"]

COPY ./pack*.json ./
COPY launcher-config.json launcher-menu.json tsconfig.json webpack.dev.js ./
COPY requirements.txt ./
COPY ./conf ./conf

ENV NODE_VERSION=22.13.0
ENV NVM_DIR=/usr/local/nvm

RUN apt-get update \
    && apt-get install -y curl \
    && mkdir -p $NVM_DIR \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && nvm install "${NODE_VERSION}" \
    && apt-get install -y sox libsox-fmt-mp3 python3-pip python3-icu python3-lxml libcairo2 \
    && npm install \
    && sed '/PyICU/d' ./requirements.txt | pip3 install -r /dev/stdin --break-system-packages \
    && pip3 install debugpy --break-system-packages \
    && python3 scripts/install/steps.py SetupKontext \
    && mkdir /var/log/rq  \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="${NVM_DIR}/versions/node/v${NODE_VERSION}/bin:${PATH}"