FROM czcorpus/kontext-manatee:2.225.8-jammy

SHELL ["/bin/bash", "--login", "-c"]

RUN apt-get update \
    && apt-get install -y curl \
    && curl -sL https://deb.nodesource.com/setup_16.x  | bash - \
    && apt-get install -y sox libsox-fmt-mp3 nodejs python3-pip python3-icu libcairo2

COPY ./requirements.txt ./
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

COPY ./pack*.json ./
RUN npm install

COPY . .
ENV KONTEXT_INSTALL_CONF=../scripts/install/conf/docker/config.cypress.xml
RUN python3 scripts/install/steps.py SetupKontext
RUN npm start build:production && npm prune --production

CMD [ "python3", "./public/app.py", "--host", "0.0.0.0", "--port", "8080", "--workers", "2" ]