FROM czcorpus/kontext-manatee

SHELL ["/bin/bash", "--login", "-c"]
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
RUN nvm install node

COPY ./pack*.json ./
RUN npm install

COPY ./conf ./conf
RUN python3 scripts/install/steps.py SetupKontext
RUN mkdir /var/log/rq

RUN apt-get install libmp3lame0 libmp3lame-dev
RUN python3 scripts/install/steps.py SetupFFMpeg

COPY . .