FROM czcorpus/kontext-manatee:2.208-jammy

WORKDIR /opt/kontext
COPY . .

RUN apt-get update \
    && apt-get install python3-pip \
    && pip3 install --upgrade pip \
    && pip3 install aiohttp \
    && pip3 install -r requirements.txt \
    && python3 scripts/install/steps.py SetupKontext

CMD [ "python3", "public/ws_app.py", "--host", "0.0.0.0" ]
