name: Python type check

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-versions: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-versions }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy -r requirements.txt
    - name: Mypy check
      run: |
        mypy lib --ignore-missing-imports
